# Generated by Django 4.2.3 on 2023-09-01 16:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blank_Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                ("published_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Blank Question",
                "verbose_name_plural": "Blank Questions",
            },
        ),
        migrations.CreateModel(
            name="Judgement_Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                ("published_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Judgement Question",
                "verbose_name_plural": "Judgement Questions",
            },
        ),
        migrations.CreateModel(
            name="Multi_Choice_Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                ("published_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Multi Choice Question",
                "verbose_name_plural": "Multi Choice Questions",
            },
        ),
        migrations.CreateModel(
            name="Short_Answer_Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                ("published_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Short Answer Question",
                "verbose_name_plural": "Short Answer Questions",
            },
        ),
        migrations.CreateModel(
            name="Short_Answer_Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=255)),
                ("answer", models.CharField(max_length=255)),
                ("score", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="question_bank.multi_choice_question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Multi_Choice_Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=255)),
                ("answer", models.CharField(max_length=255)),
                ("score", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="question_bank.multi_choice_question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Judgement_Question_Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.BooleanField(default=False)),
                ("answer", models.CharField(max_length=255)),
                ("score", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="question_bank.multi_choice_question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blank_Question_Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=255)),
                ("score", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="question_bank.multi_choice_question",
                    ),
                ),
            ],
        ),
    ]
