# Generated by Django 4.2.3 on 2023-09-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_bank", "0002_alter_blank_question_choice_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgement_question_choice",
            name="answer",
            field=models.BooleanField(default=False),
        ),
    ]
