# Generated by Django 4.2.3 on 2023-09-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_bank", "0004_alter_blank_question_choice_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="short_answer_choice",
            name="score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
    ]
