# Generated by Django 4.2.3 on 2023-09-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_bank", "0005_alter_short_answer_choice_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multi_choice_choice",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
