# Generated by Django 4.2.3 on 2023-09-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_bank", "0006_alter_multi_choice_choice_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multi_choice_choice",
            name="choice_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
