# Generated by Django 4.2.3 on 2023-09-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="student_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
